### ISSUE TITLE
Disable Cloudflare captcha

### ISSUE THREAD

**Issue by hvenev** [quicwg/quicwg.github.io#19]
I'm not sure if this is the right repository to file this issue, but can you please disable the Cloudflare captcha on https://quicwg.org/?

**Comment by larseggert** [comment]
I think the only way to do so is to turn off Cloudflare caching. @LPardue, correct?

**Comment by larseggert** [comment]
(Which we can certainly do.)

**Comment by larseggert** [comment]
OK, disabled
